### ISSUE TITLE
Consider using pydantic dataclasses for models

### ISSUE THREAD

**Issue by quantumjot** [quantumjot/btrack#120]
Why get rid of the `dateclass` structure?

_Originally posted by @paddyroddy in https://github.com/quantumjot/BayesianTracker/pull/112#discussion_r855243749_

**Comment by paddyroddy** [comment]
I've looked into this, and it is a lot of work and probably not worth it. Further, it seems that [pydantic is upgrading to v2](pydantic/pydantic#4887). I had a look into trying to upgrade to that using a beta release, but the documentation doesn't properly exist yet. Worth visiting in the future.
