### ISSUE TITLE
Mask labels in a track

### ISSUE THREAD

**Issue by markdane** [quantumjot/btrack#127]
Is there a way to identify the original mask labels  in a track? Thanks for making this package available and please let me know if there's a preferred way to ask for features or get guidance.

**Comment by quantumjot** [comment]
Hi Mark,

You should be able to use the `assign_class_ID` flag in the [segmentation_to_objects](https://btrack.readthedocs.io/en/latest/api/btrack.utils.segmentation_to_objects.html#btrack.utils.segmentation_to_objects) function to do this. From the tracks you can then get the original mask labels using:

```python
original_mask_labels = track.properties["class_id"]
```

Let me know if you have any issues

**Comment by quantumjot** [comment]
I'm going to close this
