### ISSUE TITLE
Add How-To guide for configuration

### ISSUE THREAD

**Issue by quantumjot** [quantumjot/btrack#133]
Add some How-To guides around configuration of btrack, using guidance from:
https://diataxis.fr/

Related: #124 #125 #111 #85 #31

**Comment by Ciro1990** [comment]
Any news regarding this?

Thanks
Ciro

**Comment by marabuuu** [comment]
Hi @quantumjot,

I would be also very interested in this! I have difficulties to understand the configuration parameters in napari-btrack and think this is directly related to this Issue, isn't it? :) 

Best,
Mara
