### ISSUE TITLE
Import Error for Mac M1

### ISSUE THREAD

**Issue by samueljrosen** [quantumjot/btrack#172]
Dear All,
I have been working with the example notebook for btrack and have been running into numerous problems with visualizing my final result. I either encounter one of two errors:

The first error is when I follow the installation for MacOS listed on the GitHub. I am able to successfully install napari and btrack, however I encounter errors when trying to launch the GUI. The code run smoothly until the napari viewer portion, in which I get the following:

<img width="998" alt="Screen Shot 2022-07-26 at 3 49 48 PM" src="https://user-images.githubusercontent.com/80022940/181125495-721c12f8-226c-4f80-80fd-d42370dfd38f.png">

When I try to install QtPy5 into the environment, I get the following error:

<img width="1363" alt="Screen Shot 2022-07-26 at 3 53 46 PM" src="https://user-images.githubusercontent.com/80022940/181125885-a1457b17-f347-4855-887c-7303936d2d20.png">

I am including my environment for this error, titled btrack_env.yml, such that you can replicate my error. 

Next, I tried to set up the dependencies myself by going through the environment folder and pip/conda installing the packages. I started with installing Python=3.8.13, QtPy, Napari and btrack and had success. When I went to install pyqt5, I once again ran into an installation error, which prevents me from using the gui. I get an output like the one below:

<img width="1512" alt="Screen Shot 2022-07-26 at 2 52 32 PM" src="https://user-images.githubusercontent.com/80022940/181119777-4d197b57-b600-4c2e-b94b-0fe2251eaf20.png">

I am including this environment in my zip file with the name testing.yml so you can replicate my error.

Any insight or help with instillations would be much appreciated.
[Conda_Env.zip](https://github.com/quantumjot/BayesianTracker/files/9193921/Conda_Env.zip)

**Comment by quantumjot** [comment]
Hi @samueljrosen,

Yes, it can be a bit tricky on M1. I've found the following to work:

- Start a clean conda environment
- Install napari first, using their [guidelines](https://github.com/napari/napari#installation)
- Then `conda install -c conda-forge cvxopt h5py`
- Then `pip install btrack`

Let me know if you still have issues.

**Comment by paddyroddy** [comment]
This will be fixed/documented in #306.
