### ISSUE TITLE
`GLIBC_2.29` version not found on Ubuntu 18.04

### ISSUE THREAD

**Issue by laureho** [quantumjot/btrack#198]
Using `btrack 0.5.0` on Linux Ubuntu 18.04 results in the following error message:
```OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/henriqueslab/laureho/repo_installs/BayesianTracker_branch/btrack/libs/libtracker.so)```

**Comment by quantumjot** [comment]
Hi Laure - this means that you should probably recompile it for your machine. You should be able to do the following:

```sh
git clone https://github.com/quantumjot/BayesianTracker/BayesianTracker.git
cd BayesianTracker
chmod +x ./build.sh
./build.sh
pip install -e .
```

It would be worth adding these instructions to the [documentation](https://github.com/quantumjot/BayesianTracker/blob/main/docs/user_guide/installation.rst), if you have a moment.

**Comment by markdane** [comment]
I hit the same issue yesterday and resolved it with the fix described above. Thanks!

I did remove "/BayesianTracker.git" from the URL in the first line.

**Comment by quantumjot** [comment]
> I hit the same issue yesterday and resolved it with the fix described above. Thanks!

That's great! Thanks for letting us know @markdane. We will try to fix this problem with a later update of the package (see #192 if you're interested).

**Comment by paddyroddy** [comment]
Following the merging of #231 the compiling of the libraries will be done in CI so this should be fixed
