### ISSUE TITLE
When saving 'TrackerConfig', set '.name' based on filename if it is currently 'Default'

### ISSUE THREAD

**Issue by p-j-smith** [quantumjot/btrack#243]
When creating a `TrackerConfig` [the default name is 'Default'](https://github.com/quantumjot/btrack/blob/main/btrack/config.py#L73), which means users don't have to worry about explicitly setting a name.

However, if someone saves several configs and later wants to load them into the `napari-btrack` plugin, this won't be possible if they share the same name `Default` (because config names in the gui must be unique).

The plugin could allow duplicate config names - but this would be confusing when selecting which one to use. Or, when exporting the config we could set `TrackerConfig.name` based on the filename stem if the name is currently 'Default'

**Comment by paddyroddy** [comment]
Closed in #391
