### ISSUE TITLE
Separate different steps by tabs

### ISSUE THREAD

**Issue by dpshelio** [quantumjot/btrack#266]
To use tabs to make it simpler and show other settings in tabs.

E.g., [iacs-ipac-reader ](https://www.napari-hub.org/plugins/iacs-ipac-reader) that uses Qt widgets instead of napari's magic

**Comment by paddyroddy** [comment]
starting code
```python
class PrimaryWidget(QWidget):
    """Widget to hold the t

    Args:
        QWidget: An alternative to magicgui which allows for more control
    """
    def __init__(self, napari_viewer: Viewer) -> None:
        """Instansiates the primary widget in napari.

        Args:
            napari_viewer: A napari viewer instance
        """
        super().__init__()

        self._viewer = napari_viewer
        self.setLayout(QVBoxLayout)
```

**Comment by paddyroddy** [comment]
Things to do:
- [ ] add prob not assign to motion @p-j-smith 
- [ ] `QComboBox` or similar for the `P_FP` etc. @paddyroddy 
- [ ] Ask Alan min/max values for all numeric values @paddyroddy 
- [ ] Add status bar @p-j-smith 
- [ ] Add export button (save as HDF) - what function? @p-j-smith (@quantumjot)
- [ ] Add logo w/ link to docs @paddyroddy 
- [ ] What should the heading names be? @quantumjot 
- [ ] `QGroupBox` for input, is it required? @quantumjot  
- [ ] Where to put config name? @quantumjot
