### ISSUE TITLE
Few small issues with new packaging

### ISSUE THREAD

**Issue by quantumjot** [quantumjot/btrack#291]
I tried to install this in a Docker container on a server. A few things I noticed:
+ [ ] I needed to modify the Makefile and a few headers to get it to compile in the container (see branch: https://github.com/quantumjot/btrack/tree/fix-makefile) 
+ [ ] If the user clones the repo, runs `build.sh` then `pip install .` then the newly created shared libraries are not part of the manifest. It needs to be installed in editable mode.

I'll add any others that I notice.

**Comment by paddyroddy** [comment]
Binaries are now included as of `0.5.2`

**Comment by quantumjot** [comment]
Fixed with #309
