### ISSUE TITLE
[BUG] glibc incompatibility

### ISSUE THREAD

**Issue by markdane** [quantumjot/btrack#308]
I've been using btrack in a python-based segmentation and tracking pipeline but cannot run the current version due to C++ issues. Our cluster computer runs centOS 7 with glibc 2.17. btrack is now looking for glibc 2.29. I have been researching whether I can upgrade glibc in my environment but I don't think that works. Do you know if there is a way for me to work around this issue?

**Comment by quantumjot** [comment]
Hi Mark - apologies for this. We've been having a few issues since changing some implementation details. I've made an experimental fix that should allow some backwards compatibility - could you give it a try and see if it fixes things for you?

**Comment by markdane** [comment]
This works for me using the installation instructions in #309. thanks!

**Comment by paddyroddy** [comment]
Will be fixed in #309
