### ISSUE TITLE
Cannot load tracks due to track write not exporting dummy objects

### ISSUE THREAD

**Issue by nthndy** [quantumjot/btrack#310]
The fix for this previous issue (#194) seems to have disappeared from the latest release. The fix was to simply put a `list()` around `itertools.chain.from_iterable([trk._data for trk in data])` here: https://github.com/quantumjot/btrack/blob/6cbd357ce0e0450d6a65a5bbdd3d04c266aa3058/btrack/io/hdf.py#L512-L514

**Comment by quantumjot** [comment]
Do you want to go ahead and fix this Nathan?
