### ISSUE TITLE
Minor formatting issue

### ISSUE THREAD

**Issue by nthndy** [quantumjot/btrack#311]
When localising objects from segmentation, the tqdm progress bar unecessarily prints a new line for every percent increment, resulting in a huge print out. 
This can be fixed by including `position=0` when calling tqdm. 

See: https://github.com/nthndy/btrack/commit/e81771b989fa6190e6e3296f25f60f341ed67f8b

**Comment by quantumjot** [comment]
Can you do a PR for this?
