### ISSUE TITLE
How does the "visual" TRACKING_UPDATES work without adding any user defined features to objects?

### ISSUE THREAD

**Issue by Sagnik700** [quantumjot/btrack#324]
Hello all,

I am trying to get the tracking result for a live cell dataset, keeping the TRACKING_UPDATES list value to only _visual_. From the documentation I can see that it says - `visual - this uses the features supplied to link objects in time` - [link](https://btrack.readthedocs.io/en/latest/user_guide/using_features.html#:~:text=objects%20in%20time-,visual,-%2D%20this%20uses%20the)

But even if I do not add any features to objects, either by [built-in functions](https://btrack.readthedocs.io/en/latest/user_guide/using_features.html#using-built-in-functions) or with [user defined features](https://btrack.readthedocs.io/en/latest/user_guide/using_features.html#using-built-in-functions), the tracking seems to work. Since the documentation says that the visual setting uses features supplied to link objects in time, I don't quite understand what is it exactly using in its logic when no features are additionaly supplied to the objects. It will be great if someone can clarify my doubts over this. Thanks in advance.

Posting a minimal reproducible example for better understanding:

    objects = btrack.utils.segmentation_to_objects(segmentation)

    # this is the default tracking config from
    # https://github.com/quantumjot/BayesianTracker/blob/main/models/cell_config.json
    config_file = "./cell_config.json"

    with btrack.BayesianTracker() as tracker:
        tracker.configure_from_file(config_file)
      
        tracker.append(objects)
        shape = segmentation.shape[1:]
        volume = ((0, shape[1]), (0, shape[0]))
        tracker.volume = volume

        tracker.track(tracking_updates=['visual'])

        tracker.optimize()

        btrack.io.export_CSV(filename='../results_updated/1/results_v1.csv',
                             tracks=tracker.tracks, obj_type='obj_type_1')

**Comment by quantumjot** [comment]
Hi @Sagnik700 - sorry I didn't respond sooner. I've been working on some other things.  The tracking will most likely still work even if you do not supply any visual features. Certainly, the optimization step will try to stitch things together based on the hypotheses generated - some of these do not require any additional information other than the spatial and temporal coordinates of the objects. So if you have those at a minimum, then you will always get *some* output, it's just not necessarily very good.

**Comment by Sagnik700** [comment]
Thanks for the clarification @quantumjot . Closing this issue now.
