### ISSUE TITLE
[FEATURE REQUEST] Set default value of p(not track)

### ISSUE THREAD

**Issue by quantumjot** [quantumjot/btrack#372]
should be: 0.1

**Comment by p-j-smith** [comment]
Sorry you may have missed it, but I mentioned in #357 that this widget has:

> ...a default value of 0.001, as this is the value used by the [cell](https://raw.githubusercontent.com/lowe-lab-ucl/btrack-examples/main/examples/cell_config.json) and [particle](https://raw.githubusercontent.com/lowe-lab-ucl/btrack-examples/main/examples/particle_config.json) example configs (which we load into the plugin at launch)

Would it be possible to update the values in the [example configs](https://github.com/lowe-lab-ucl/btrack-examples/tree/main/examples), just so we don't have to maintain a separate set of defaults?

**Comment by p-j-smith** [comment]
> I've changed in both for now. But it doesn't update in the widget. Any idea @p-j-smith?

the cell and particle example configs are loaded when the plugin is launched, and the cell config is then selected. This then sets all the widget values (effectively setting the defaults)

**Comment by paddyroddy** [comment]
Okay but for now I've changed it everywhere so why is it showing `0.001`? Checkout my PR and see for yourself

**Comment by paddyroddy** [comment]
There you go. Related #375

**Comment by p-j-smith** [comment]
> There you go. Related https://github.com/quantumjot/btrack/issues/375

I think the ones in `models/` aren't being used. We using the `datasets` module to load the example configs, which takes them from:

https://github.com/quantumjot/btrack/blob/003407e00569e3718aceacc849036835f477a121/btrack/datasets.py#L11
