### ISSUE TITLE
[FEATURE REQUEST] Should example configs be taken from `lowe-lab-ucl/btrack-examples`?

### ISSUE THREAD

**Issue by paddyroddy** [quantumjot/btrack#375]
Should we avoid duplication and pull the config files from https://github.com/lowe-lab-ucl/btrack-examples rather than store them here https://github.com/quantumjot/btrack/tree/main/models?

**Comment by quantumjot** [comment]
Yes, I think so

**Comment by paddyroddy** [comment]
Fixed in #374
