### ISSUE TITLE
[BUG] `volume` isn't set as expected, in the `test_tracker_graph` test

### ISSUE THREAD

**Issue by paddyroddy** [quantumjot/btrack#387]
In `tests/_utils.py` `volume` is not being set properly
https://github.com/quantumjot/btrack/blob/2ec77286676c5fb65458f7d4fa59beb089906a2e/tests/_utils.py#L220
It should be `tracker.configuration.volume = ((0, 1600), (0, 1200), (-1e5, 1e5))`

I tried running this myself, and it resulted in this error
https://github.com/quantumjot/btrack/actions/runs/5799240691/job/15718872998
So clearly `volume` is being set as expected in the `test_tracker_graph` test

**Comment by quantumjot** [comment]
I don't think this is the source of the error, see the slack note about setting the motion model params

**Comment by paddyroddy** [comment]
But do you agree `volume` isn't being set?

**Comment by quantumjot** [comment]
> But do you agree volume isn't being set?

I checked it and it is being set.  The core tracker has a rather complicated `__setattr__` method which takes care of things like this:

https://github.com/quantumjot/btrack/blob/2ec77286676c5fb65458f7d4fa59beb089906a2e/btrack/core.py#L196-L216

**Comment by paddyroddy** [comment]
Okay, cool. Closing!
