### ISSUE TITLE
Overlap issue of instance segmentation masks

### ISSUE THREAD

**Issue by yufang1039** [quantumjot/btrack#50]
Hello! Thank you for this great tracker. 

I have a question about the segmentation that this tracker accepts. It seems like according to the example you gave and what I have tried, I have to put all the instance masks in one layer and pass it to the tracker. However, if there's overlap between two cell instances, the tracker will consider them as the same cell. Does it mean I have to remove all the overlaps before passing them to the tracker? Separation of cell instances is really important to me.

Thank you in advance!

**Comment by quantumjot** [comment]
Hi! If you have a mask where each object has a unique ID (e.g. output from stardist) then it should work fine. You only need to make sure they're not touching in the case of a binary mask.
