### ISSUE TITLE
Generator Error (_is_binary)

### ISSUE THREAD

**Issue by yufang1039** [quantumjot/btrack#86]
When I'm using generator and pass it to btrack.utils.segmentation_to_objects, there's a strange error appears. I can't even find this function in the source code.

~\anaconda3\envs\pytorch_venv\lib\site-packages\btrack\_localization.py in _is_binary(x)
     46 
     47     def _is_binary(x: np.ndarray) -> bool:
---> 48         return ((x == 0) | (x == 1)).all()
     49 
     50     if use_weighted_centroid and intensity_image is not None:

AttributeError: 'bool' object has no attribute 'all'

**Comment by quantumjot** [comment]
Hi there, can you post a code snippet to show the generator? It looks like you're passing a single bool rather than a numpy array.

**Comment by paddyroddy** [comment]
Closing as no follow up. Feel free to respond when possible.
